### ISSUE TITLE
Add Chat Bots

### ISSUE THREAD

**Issue by arbox** [arbox/nlp-with-ruby#1]
Add chat bots by @solyaris.

**Comment by solyarisoftware** [comment]
Hi Andrei

thanks for mentioning; just for my curiosity:  

1. the issue here is to remind to yourself to add a specific chapter for a topic about chatbots?

2. BTW, I help to update the Kevin Diask  repo: https://github.com/diasks2/ruby-nlp

Is https://github.com/arbox/nlp-with-ruby a fork of that above in the way you described here: https://github.com/arbox/nlp-with-ruby/blob/master/motivation.md ?

I'll reteet your repo anyway :) twitter.com/solyarisoftware

respect
giorgio

**Comment by arbox** [comment]
Hi Giorgio,

thank you for your attention!

Yes, this issue is a reminder as you pointed out. You invested a lot of your personal dedication and time into that topic, so I wanted to incorporate your knowledge.

As for the excellent resource by Kevin Dias, I think both list are complementary. The primary goal of this list is not to collect all possible **good** things but to provide at least one **solid** solution for every task.  We're on this way and plan to write tutorials for every NLP Pipeline step and applied task.

The other very important point is to enhance the visibility of Ruby for NLP and other related tasks since Python is dominating this area today. Again two resources are better that one to make the topic more visible.

As for the motivation It's mostly our decision to invest time on the weekly basis and provide an up to date project where at least:
- all links are correct
- all projects are actively maintained
- every point is documented.

Most resources do _not_ even check links regularly or/and are updated frequently. 

Let's see if we could achieve  this goal :) Any help welcome!

**Comment by solyarisoftware** [comment]
Thanks to you Andrei

I see your points and I agree.

Soon I'll read with attention your repo.

About chatbots dev, and just to enhance the visibility of Ruby for NLP, I'm coding myself a very simple tool in Ruby: [naif](https://github.com/solyaris/naif) and I'll publish soon source code on github.

BTW, I write often on [twitter](https://www.twitter.com/solyarisoftware), 
and I just [published a tweet about this repo](https://twitter.com/solyarisoftware/status/817387416327782402): 

Please feel free to contact me via [mail](mailto:giorgio.robino@gmail.com).

respect
giorgio

**Comment by arbox** [comment]
Thank you for you inputs!

There are two things we could do concerning your new chatbot framework:

1. you could write a tutorial for this list which will be linked to your repo, not necessarily long (feel free to reuse this text for your repo documentation since you need a tutorial anyway),
2. consider including a badge in the Header line (it's up to you but it creates a network of RubyNLP resouces) [![Awesome RubyNLP](https://img.shields.io/badge/Awesome-RubyNLP-brightgreen.svg)](https://github.com/arbox/nlp-with-ruby) like in the Stanford CoreNLP repo: https://github.com/louismullie/stanford-core-nlp

**Comment by solyarisoftware** [comment]
OK! I'll follow your suggestion, as soon I have a decent naif release to publish :-)

**Comment by arbox** [comment]
Done!
